---
title: "ClassifyMethod_EZ"
author: "Eleanor Zhang"
date: "5/9/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 7,fig.asp = .7,out.width = "90%",
                      message = FALSE, warning = FALSE)
library(tidyverse)
library(ggridges)
library(caret)
library(boot)
library(pls)
library(glmnet)
library(splines)
library(mgcv)
library(MASS)
library(GGally)
library(RColorBrewer)
theme_set(theme_classic())

```

## Data 

Binary outcome
```{r}
apple <- read_csv("./data/AppleStore.csv") %>%
  janitor::clean_names() %>%
  dplyr::select(-c(x1, id, track_name, currency, ver)) %>%
  mutate(size_bytes = round(size_bytes * 1e-6),
         cont_rating = factor(cont_rating, levels = c("4+", "9+","12+","17+")),
         user_rating = ifelse(user_rating >= 4, 1, 0)) %>%
  rename(size_megabytes = size_bytes) %>%
  filter(rating_count_tot != 0,
         user_rating_ver != 0) %>% #Remove apps with no user rating
  mutate(prime_genre = as.integer(ifelse(prime_genre == "Games", 1, 0))) %>% 
  dplyr::select(-rating_count_tot, -rating_count_ver, -vpp_lic) #vpp_lic has nearzero variance

str(apple)
table(apple$user_rating)
```

split data

```{r}
set.seed(1234)
#Split data to traning and testing
trRows = createDataPartition(apple$user_rating,
                             p = .75,
                             list = FALSE)
train_data = apple[trRows,]
test_data = apple[-trRows,]
#in matrix form
x_train = model.matrix(user_rating~., train_data)[,-1] 
y_train = train_data$user_rating
x_test = model.matrix(user_rating~., test_data)[,-1] 
y_test = test_data$user_rating

ctrl1 = trainControl(method = "cv", number = 10)
```

continous outcome
```{r}
apple1 <- read_csv("./data/AppleStore.csv") %>%
  janitor::clean_names() %>%
  dplyr::select(-c(x1, id, track_name, currency, ver)) %>%
  mutate(size_bytes = round(size_bytes * 1e-6),
         cont_rating = factor(cont_rating, levels = c("4+", "9+","12+","17+")))%>%
  rename(size_megabytes = size_bytes) %>%
  filter(rating_count_tot != 0,
         user_rating_ver != 0) %>% #Remove apps with no user rating
  mutate(prime_genre = as.integer(ifelse(prime_genre == "Games", 1, 0))) %>% 
  dplyr::select(-rating_count_tot, -rating_count_ver, -vpp_lic) #vpp_lic has nearzero variance

str(apple1)

train_data1 = apple1[trRows,]
test_data1 = apple1[-trRows,]
#in matrix form
x_train1 = model.matrix(user_rating~., train_data1)[,-1] 
y_train1 = train_data1$user_rating
x_test1 = model.matrix(user_rating~., test_data1)[,-1] 
y_test1 = test_data1$user_rating
```

## Data descriptions

size megabytes is right skewed, mostly less than 1000 mb;  
price is right skewed, most less than $10;  
overall user rating is left skewed; recode into binary variable as either high rating(>= 4) or low (<4) user rating of current version




## Linear Methods for Classification

### graphics


### logistic regression


